[project]
name = "pydantic-ai-history-summarizer"
version = "0.1.0"
description = "History summarizer agent example"
requires-python = ">=3.13"
dependencies = [
    "logfire>=4.14.2",
    "pydantic-ai>=1.7.0",
    "uuid>=1.30",
]
