[project]
name = "pydantic-ai-evaluations"
version = "0.1.0"
description = "Pydantic AI evaluations example"
requires-python = ">=3.13"
dependencies = [
    "logfire>=4.14.2",
    "pydantic-ai>=1.7.0",
    "pydantic-evals>=1.7.0",
]
