[project]
name = "pydantic-ai-extended-planner"
version = "0.1.0"
description = "Extended planner agent example"
requires-python = ">=3.13"
dependencies = [
    "logfire>=4.14.2",
    "numexpr>=2.14.1",
    "pydantic-ai>=1.7.0",
    "pydantic-ai-slim[duckduckgo]>=1.7.0",
]
